depends_on:
  - xtracfg-build

when:
  event: push

pipeline:

  load:
    #image: woodpeckerci/plugin-s3
    image: docker.ci.interactive-instruments.de/cicd/drone-s3
    pull: true
    settings:
      download: true
      path_style: true
      endpoint: https://s3.ldproxy.net
      bucket: woodpecker
      access_key: qluSRa6nIanEr6KY9wzf
      secret_key: OmlgXE781FszEKLycVACn7mGe6yWYER29iNWxe2l
      strip_prefix: xtracfg/
      target: /xtracfg

  github:
    image: woodpeckerci/plugin-github-release
    settings:
      draft: true
      files:
        - xtracfg/linux/amd64/xtracfg
        - xtracfg/linux/arm64/xtracfg
      title: snapshot (${CI_COMMIT_SHA})
      api-key:
        from_secret: github_token

  docker:
    image: woodpeckerci/plugin-docker-buildx
    # TODO: see https://codeberg.org/woodpecker-plugins/docker-buildx/issues/50
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    settings:
      registry: ghcr.io
      repo: ghcr.io/ldproxy/xtracfg
      tags: next
      force_tag: true
      pull_image: true
      dockerfile: xtracfg/Dockerfile
      context: xtracfg
      platforms:
        - linux/amd64
        - linux/arm64
      logins:
        # needed to pull ni-base
        - registry: ghcr.io
          username:
            from_secret: ghcr_username
          password:
            from_secret: ghcr_password
