when:
  event: push


pipeline:
  bin:
    image: ghcr.io/ldproxy/golang-jdk:1.2
    commands:
      - cd xtractl
      - GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o dist/linux-amd64/xtractl
      - GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o dist/linux-arm64/xtractl
      - ls -laR dist

  #github:
  #  image: meltwaterfoundation/github-cli:2.29.0
  #  commands:
  #    - gh release create next --title next --draft "xtractl/dist/linux-amd64/xtractl#xtractl (linux/amd64)" "xtractl/dist/linux-arm64/xtractl#xtractl (linux/arm64)"
  #  secrets: [github_token]

  docker:
    image: woodpeckerci/plugin-docker-buildx
    # TODO: see https://codeberg.org/woodpecker-plugins/docker-buildx/issues/50
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    settings:
      registry: ghcr.io
      repo: ghcr.io/ldproxy/xtractl
      tags: next
      force_tag: true
      pull_image: true
      dockerfile: xtractl/Dockerfile
      context: xtractl/dist
      platforms:
        - linux/amd64
        - linux/arm64
      logins:
        - registry: ghcr.io
          username:
            from_secret: ghcr_username
          password:
            from_secret: ghcr_password
