when:
  event: push

matrix:
  include:
    - platform: linux/amd64
      suffix: -amd64 
    - platform: linux/arm64
      suffix: ''
#    - platform: darwin/arm64
#      image: bash
#      # override default /cache/gradle which does not exist on local
#      setup: export GRADLE_USER_HOME=$${CI_WORKSPACE}/.gradle

platform: ${platform}

pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./xtracfg/build/dist
    volumes:
      - /tmp/cache:/cache

  lib:
    image: ghcr.io/ldproxy/golang-jdk:1.2
    commands:
      - cd xtracfg
      - CGO_CFLAGS="-I$JAVA_HOME/include -I$JAVA_HOME/include/linux" go build -ldflags="-s -w '-extldflags=-z noexecstack'" -buildmode c-archive -o dist/libxtracfg.a
      - ls -la dist

  bin:
    image: ghcr.io/ldproxy/liberica-nik:22-jdk11
    commands:
      - cd xtracfg
      - ./gradlew nativeCompile
      - ls -la build/native/nativeCompile

  upx:
    image: harshavardhanj/upx:3.95
    commands:
      - cd xtracfg
      - upx --brute build/native/nativeCompile/xtracfg
      - mkdir -p build/dist/${platform}/
      - cp build/native/nativeCompile/xtracfg build/dist/${platform}/
      - ls -la build/dist/${platform}/

  github:
    image: meltwaterfoundation/github-cli:2.29.0
    commands:
      - gh release create next --title "xtracfg snapshot (${platform})" --draft "xtracfg/build/native/nativeCompile/xtracfg#xtracfg (${platform})"
    secrets: [github_token]

  docker:
    image: woodpeckerci/plugin-docker-buildx
    # TODO: see https://codeberg.org/woodpecker-plugins/docker-buildx/issues/50
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    settings:
      registry: ghcr.io
      repo: ghcr.io/ldproxy/xtracfg
      tags: next
      force_tag: true
      pull_image: true
      dockerfile: xtracfg/Dockerfile
      context: xtracfg/build/dist
      platforms:
        - linux/amd64
        - linux/arm64
      logins:
        # needed to pull ni-base
        - registry: ghcr.io
          username:
            from_secret: ghcr_username
          password:
            from_secret: ghcr_password
    when:
      platform: linux/arm64

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./xtracfg/build/dist
    volumes:
      - /tmp/cache:/cache
