when:
  event: [push,tag]

matrix:
  include:
    - platform: linux/amd64
    - platform: linux/arm64
#    - platform: darwin/arm64
#      image: bash
#      # override default /cache/gradle which does not exist on local
#      setup: export GRADLE_USER_HOME=$${CI_WORKSPACE}/.gradle

platform: ${platform}

pipeline:

  lib:
    image: ghcr.io/ldproxy/golang-jdk:1.2
    commands:
      - cd xtracfg
      - CGO_CFLAGS="-I$JAVA_HOME/include -I$JAVA_HOME/include/linux" go build -ldflags="-s -w '-extldflags=-z noexecstack'" -buildmode c-archive -o dist/libxtracfg.a

  bin:
    image: ghcr.io/ldproxy/liberica-nik:22-jdk11
    commands:
      - cd xtracfg
      - ./gradlew nativeCompile

  upx:
    image: docker.ci.interactive-instruments.de/cicd/upx
    commands:
      - cd xtracfg
      - upx --best build/native/nativeCompile/xtracfg

  save:
    #image: woodpeckerci/plugin-s3
    image: docker.ci.interactive-instruments.de/cicd/drone-s3
    settings:
      path_style: true
      endpoint: https://s3.ldproxy.net
      bucket: woodpecker
      target: /xtracfg/${platform}
      source: xtracfg/build/native/nativeCompile/xtracfg
      strip_prefix: xtracfg/build/native/nativeCompile
      access_key: qluSRa6nIanEr6KY9wzf
      secret_key: OmlgXE781FszEKLycVACn7mGe6yWYER29iNWxe2l
