depends_on:
  - xtracfg-build

when:
  event: push

pipeline:

  load:
    #image: woodpeckerci/plugin-s3
    image: docker.ci.interactive-instruments.de/cicd/drone-s3
    pull: true
    settings:
      download: true
      path_style: true
      endpoint: https://s3.ldproxy.net
      bucket: woodpecker
      target: /xtracfg
      strip_prefix: xtracfg/
      access_key: qluSRa6nIanEr6KY9wzf
      secret_key: OmlgXE781FszEKLycVACn7mGe6yWYER29iNWxe2l

  github:
    image: meltwaterfoundation/github-cli:2.29.0
    commands:
      - gh release create next --title "xtracfg snapshot (linux/amd64)" --draft "xtractl/dist/linux-amd64/xtractl#xtractl (linux/amd64)"
      - gh release create next --title "xtracfg snapshot (linux/arm64)" --draft "xtractl/dist/linux-arm64/xtractl#xtractl (linux/arm64)"
    secrets: [github_token]

  docker:
    image: woodpeckerci/plugin-docker-buildx
    # TODO: see https://codeberg.org/woodpecker-plugins/docker-buildx/issues/50
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    settings:
      registry: ghcr.io
      repo: ghcr.io/ldproxy/xtracfg
      tags: next
      force_tag: true
      pull_image: true
      dockerfile: xtracfg/Dockerfile
      context: xtracfg
      platforms:
        - linux/amd64
        - linux/arm64
      logins:
        # needed to pull ni-base
        - registry: ghcr.io
          username:
            from_secret: ghcr_username
          password:
            from_secret: ghcr_password
