when:
  event: tag


pipeline:
  bin:
    image: ghcr.io/ldproxy/golang-jdk:1.2
    commands:
      - cd xtractl
      - GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o dist/linux-amd64/xtractl
      - GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o dist/linux-arm64/xtractl

  upx:
    image: harshavardhanj/upx:3.95
    commands:
      - upx --brute xtractl/dist/linux-amd64/xtractl
      - upx --brute xtractl/dist/linux-arm64/xtractl

  github:
    image: meltwaterfoundation/github-cli:2.29.0
    commands:
      - gh release create ${CI_COMMIT_TAG} --title ${CI_COMMIT_TAG} --draft 
      - gh release upload ${CI_COMMIT_TAG} "xtractl/dist/linux-amd64/xtractl#xtractl (linux/amd64)"
      - gh release upload ${CI_COMMIT_TAG} "xtractl/dist/linux-arm64/xtractl#xtractl (linux/arm64)"
    secrets: [github_token]

  docker:
    image: woodpeckerci/plugin-docker-buildx
    # TODO: see https://codeberg.org/woodpecker-plugins/docker-buildx/issues/50
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    settings:
      registry: ghcr.io
      repo: ghcr.io/ldproxy/xtractl
      auto_tag: true
      force_tag: true
      pull_image: true
      dockerfile: xtractl/Dockerfile
      context: xtractl/dist
      platforms:
        - linux/amd64
        - linux/arm64
      logins:
        - registry: ghcr.io
          username:
            from_secret: ghcr_username
          password:
            from_secret: ghcr_password
