depends_on:
  - xtracfg-build

when:
  event: push

steps:
  load:
    #image: woodpeckerci/plugin-s3
    image: docker.ci.interactive-instruments.de/cicd/drone-s3
    pull: true
    settings:
      download: true
      path_style: true
      endpoint: https://s3.ldproxy.net
      bucket: woodpecker
      target: /xtracfg
      strip_prefix: xtracfg/${CI_COMMIT_BRANCH}/
      access_key: qluSRa6nIanEr6KY9wzf
      secret_key: OmlgXE781FszEKLycVACn7mGe6yWYER29iNWxe2l

  #  github:
  #    image: meltwaterfoundation/github-cli:2.29.0
  #    commands:
  #      - chmod +x xtracfg/linux/amd64/xtracfg
  #      - chmod +x xtracfg/linux/arm64/xtracfg
  #      - tar -czvf xtracfg_${CI_COMMIT_SHA:0:8}_linux_amd64.tar.gz -C xtracfg/linux/amd64 xtracfg
  #      - tar -czvf xtracfg_${CI_COMMIT_SHA:0:8}_linux_arm64.tar.gz -C xtracfg/linux/arm64 xtracfg
  #      - gh release upload ${CI_COMMIT_SHA:0:8} xtracfg_${CI_COMMIT_SHA:0:8}_linux_amd64.tar.gz
  #      - gh release upload ${CI_COMMIT_SHA:0:8} xtracfg_${CI_COMMIT_SHA:0:8}_linux_arm64.tar.gz
  #    secrets: [github_token]

  docker-main:
    image: woodpeckerci/plugin-docker-buildx
    # TODO: see https://codeberg.org/woodpecker-plugins/docker-buildx/issues/50
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    settings:
      registry: ghcr.io
      repo: ghcr.io/ldproxy/xtracfg
      tags:
        - next
        - next-${CI_COMMIT_SHA:0:8}
      force_tag: true
      pull_image: true
      dockerfile: xtracfg/Dockerfile
      context: xtracfg
      platforms:
        - linux/amd64
        - linux/arm64
      logins:
        # needed to pull ni-base
        - registry: ghcr.io
          username:
            from_secret: ghcr_username
          password:
            from_secret: ghcr_password
    when:
      - branch: main

  docker-branch:
    image: woodpeckerci/plugin-docker-buildx
    # TODO: see https://codeberg.org/woodpecker-plugins/docker-buildx/issues/50
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    settings:
      registry: ghcr.io
      repo: ghcr.io/ldproxy/xtracfg
      tags:
        - ${CI_COMMIT_BRANCH}
        - ${CI_COMMIT_BRANCH}-${CI_COMMIT_SHA:0:8}
      force_tag: true
      pull_image: true
      dockerfile: xtracfg/Dockerfile
      context: xtracfg/dist
      platforms:
        - linux/amd64
        - linux/arm64
      logins:
        - registry: ghcr.io
          username:
            from_secret: ghcr_username
          password:
            from_secret: ghcr_password
    when:
      - branch: maintenance-*
