when:
  event: tag

matrix:
  include:
    - platform: linux/amd64
      suffix: -amd64 
    - platform: linux/arm64
      suffix: ''
#    - platform: darwin/arm64
#      image: bash
#      # override default /cache/gradle which does not exist on local
#      setup: export GRADLE_USER_HOME=$${CI_WORKSPACE}/.gradle

platform: ${platform}

pipeline:
  lib:
    image: ghcr.io/ldproxy/golang-jdk:1.2
    commands:
      - cd xtracfg
      - CGO_CFLAGS="-I$JAVA_HOME/include -I$JAVA_HOME/include/linux" go build -ldflags="-s -w '-extldflags=-z noexecstack'" -buildmode c-archive -o dist/libxtracfg.a
      - ls -la dist

  bin:
    image: ghcr.io/ldproxy/liberica-nik:22-jdk11
    commands:
      - cd xtracfg
      - ./gradlew nativeCompile
      - ls -la build/native/nativeCompile

  github:
    image: meltwaterfoundation/github-cli:2.29.0
    commands:
      - gh release create next --title next --draft "xtracfg/build/native/nativeCompile/xtracfg#xtracfg (${platform})"
    secrets: [github_token]

  docker:
    image: woodpeckerci/plugin-docker-buildx
    # TODO: see https://codeberg.org/woodpecker-plugins/docker-buildx/issues/50
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    settings:
      registry: docker.ci.interactive-instruments.de
      repo: docker.ci.interactive-instruments.de/iide/xtracfg${suffix}
      tags: latest
      force_tag: true
      dockerfile: xtracfg/Dockerfile
      context: xtracfg/build/native/nativeCompile
      pull_image: true
      platforms:
        - ${platform}
      logins:
        # needed to pull ni-base
        - registry: ghcr.io
          username:
            from_secret: ghcr_username
          password:
            from_secret: ghcr_password
