when:
  event: tag

steps:
  bin:
    image: ghcr.io/ldproxy/golang-jdk:1.2
    commands:
      - cd xtractl
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o dist/linux-amd64/xtractl -ldflags="-s -w -X github.com/interactive-instruments/xtraplatform-cli/xtractl/cmd.gitTag=${CI_COMMIT_TAG} -X github.com/interactive-instruments/xtraplatform-cli/xtractl/cmd.gitSha=${CI_COMMIT_SHA} -X github.com/interactive-instruments/xtraplatform-cli/xtractl/cmd.gitBranch=${CI_COMMIT_BRANCH}"
      - CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o dist/linux-arm64/xtractl -ldflags="-s -w -X github.com/interactive-instruments/xtraplatform-cli/xtractl/cmd.gitTag=${CI_COMMIT_TAG} -X github.com/interactive-instruments/xtraplatform-cli/xtractl/cmd.gitSha=${CI_COMMIT_SHA} -X github.com/interactive-instruments/xtraplatform-cli/xtractl/cmd.gitBranch=${CI_COMMIT_BRANCH}"

  upx:
    image: docker.ci.interactive-instruments.de/cicd/upx
    commands:
      - upx --best xtractl/dist/linux-amd64/xtractl
      - upx --best xtractl/dist/linux-arm64/xtractl

  github:
    image: meltwaterfoundation/github-cli:2.29.0
    commands:
      - chmod +x xtractl/dist/linux-amd64/xtractl
      - chmod +x xtractl/dist/linux-arm64/xtractl
      - tar -czvf xtractl_${CI_COMMIT_TAG}_linux_amd64.tar.gz -C xtractl/dist/linux-amd64 xtractl
      - tar -czvf xtractl_${CI_COMMIT_TAG}_linux_arm64.tar.gz -C xtractl/dist/linux-arm64 xtractl
      - gh release create ${CI_COMMIT_TAG} --title ${CI_COMMIT_TAG} --draft
      - gh release upload ${CI_COMMIT_TAG} xtractl_${CI_COMMIT_TAG}_linux_amd64.tar.gz
      - gh release upload ${CI_COMMIT_TAG} xtractl_${CI_COMMIT_TAG}_linux_arm64.tar.gz
    secrets: [github_token]

  docker:
    image: woodpeckerci/plugin-docker-buildx
    # TODO: see https://codeberg.org/woodpecker-plugins/docker-buildx/issues/50
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    settings:
      registry: ghcr.io
      repo: ghcr.io/ldproxy/xtractl
      auto_tag: true
      force_tag: true
      pull_image: true
      dockerfile: xtractl/Dockerfile
      context: xtractl/dist
      platforms:
        - linux/amd64
        - linux/arm64
      logins:
        - registry: ghcr.io
          username:
            from_secret: ghcr_username
          password:
            from_secret: ghcr_password
