when:
  event: push

matrix:
  include:
    - platform: linux/amd64
    - platform: linux/arm64
#    - platform: darwin/arm64
#      image: bash
#      # override default /cache/gradle which does not exist on local
#      setup: export GRADLE_USER_HOME=$${CI_WORKSPACE}/.gradle

platform: ${platform}

pipeline:

  lib:
    image: ghcr.io/ldproxy/golang-jdk:1.2
    commands:
      - cd xtracfg
      - CGO_CFLAGS="-I$JAVA_HOME/include -I$JAVA_HOME/include/linux" go build -ldflags="-s -w '-extldflags=-z noexecstack'" -buildmode c-archive -o dist/libxtracfg.a
      - ls -la dist

  bin:
    image: ghcr.io/ldproxy/liberica-nik:22-jdk11
    commands:
      - cd xtracfg
      - ./gradlew nativeCompile
      - ls -la build/native/nativeCompile

  upx:
    image: harshavardhanj/upx:3.95
    commands:
      - cd xtracfg
#      - upx --brute build/native/nativeCompile/xtracfg
      - mkdir -p build/dist/${platform}/
      - cp build/native/nativeCompile/xtracfg build/dist/${platform}/
      - ls -laR build/dist/

  save:
    image: woodpeckerci/plugin-s3
    settings:
      debug: true
      rebuild: true
      endpoint: https://s3.ldproxy.net
      bucket: woodpecker
      access_key: qluSRa6nIanEr6KY9wzf
      secret_key: OmlgXE781FszEKLycVACn7mGe6yWYER29iNWxe2l
      source: build/dist/${platform}
      target: ${CI_WORKSPACE}/${platform}
